/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfaz;

import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author user
 */
public class IntFrmContabilidad extends javax.swing.JInternalFrame {
Object parent;
    /**
     * Creates new form IntFrmContabilidad
     */
    public IntFrmContabilidad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        DesktopPanePlanCuentas = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        DesktopPaneLibroDiario = new javax.swing.JDesktopPane();
        jPanel3 = new javax.swing.JPanel();
        DesktopPaneAsientoContable = new javax.swing.JDesktopPane();
        jPanel4 = new javax.swing.JPanel();
        DesktopPaneLibroMayor = new javax.swing.JDesktopPane();
        jPanel5 = new javax.swing.JPanel();
        DesktopPaneBalanceComprobacion = new javax.swing.JDesktopPane();
        jPanel6 = new javax.swing.JPanel();
        DesktopPaneBalanceGeneral = new javax.swing.JDesktopPane();
        jPanel7 = new javax.swing.JPanel();
        DesktopPaneBalanceResultados = new javax.swing.JDesktopPane();

        setBorder(null);

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTabbedPane1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout DesktopPanePlanCuentasLayout = new javax.swing.GroupLayout(DesktopPanePlanCuentas);
        DesktopPanePlanCuentas.setLayout(DesktopPanePlanCuentasLayout);
        DesktopPanePlanCuentasLayout.setHorizontalGroup(
            DesktopPanePlanCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 649, Short.MAX_VALUE)
        );
        DesktopPanePlanCuentasLayout.setVerticalGroup(
            DesktopPanePlanCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 318, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPanePlanCuentas)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPanePlanCuentas)
        );

        jTabbedPane1.addTab("Plan de Cuentas", jPanel1);

        javax.swing.GroupLayout DesktopPaneLibroDiarioLayout = new javax.swing.GroupLayout(DesktopPaneLibroDiario);
        DesktopPaneLibroDiario.setLayout(DesktopPaneLibroDiarioLayout);
        DesktopPaneLibroDiarioLayout.setHorizontalGroup(
            DesktopPaneLibroDiarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 649, Short.MAX_VALUE)
        );
        DesktopPaneLibroDiarioLayout.setVerticalGroup(
            DesktopPaneLibroDiarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 318, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPaneLibroDiario)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPaneLibroDiario, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jTabbedPane1.addTab("Libro Diario", jPanel2);

        javax.swing.GroupLayout DesktopPaneAsientoContableLayout = new javax.swing.GroupLayout(DesktopPaneAsientoContable);
        DesktopPaneAsientoContable.setLayout(DesktopPaneAsientoContableLayout);
        DesktopPaneAsientoContableLayout.setHorizontalGroup(
            DesktopPaneAsientoContableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 649, Short.MAX_VALUE)
        );
        DesktopPaneAsientoContableLayout.setVerticalGroup(
            DesktopPaneAsientoContableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 318, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPaneAsientoContable)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPaneAsientoContable)
        );

        jTabbedPane1.addTab("Asientos Contable", jPanel3);

        javax.swing.GroupLayout DesktopPaneLibroMayorLayout = new javax.swing.GroupLayout(DesktopPaneLibroMayor);
        DesktopPaneLibroMayor.setLayout(DesktopPaneLibroMayorLayout);
        DesktopPaneLibroMayorLayout.setHorizontalGroup(
            DesktopPaneLibroMayorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 649, Short.MAX_VALUE)
        );
        DesktopPaneLibroMayorLayout.setVerticalGroup(
            DesktopPaneLibroMayorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 318, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPaneLibroMayor)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPaneLibroMayor)
        );

        jTabbedPane1.addTab("Libro Mayor", jPanel4);

        javax.swing.GroupLayout DesktopPaneBalanceComprobacionLayout = new javax.swing.GroupLayout(DesktopPaneBalanceComprobacion);
        DesktopPaneBalanceComprobacion.setLayout(DesktopPaneBalanceComprobacionLayout);
        DesktopPaneBalanceComprobacionLayout.setHorizontalGroup(
            DesktopPaneBalanceComprobacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 649, Short.MAX_VALUE)
        );
        DesktopPaneBalanceComprobacionLayout.setVerticalGroup(
            DesktopPaneBalanceComprobacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 318, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPaneBalanceComprobacion)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPaneBalanceComprobacion)
        );

        jTabbedPane1.addTab("Balance Comprobacion", jPanel5);

        javax.swing.GroupLayout DesktopPaneBalanceGeneralLayout = new javax.swing.GroupLayout(DesktopPaneBalanceGeneral);
        DesktopPaneBalanceGeneral.setLayout(DesktopPaneBalanceGeneralLayout);
        DesktopPaneBalanceGeneralLayout.setHorizontalGroup(
            DesktopPaneBalanceGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 649, Short.MAX_VALUE)
        );
        DesktopPaneBalanceGeneralLayout.setVerticalGroup(
            DesktopPaneBalanceGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 318, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPaneBalanceGeneral)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPaneBalanceGeneral)
        );

        jTabbedPane1.addTab("Balance General", jPanel6);

        javax.swing.GroupLayout DesktopPaneBalanceResultadosLayout = new javax.swing.GroupLayout(DesktopPaneBalanceResultados);
        DesktopPaneBalanceResultados.setLayout(DesktopPaneBalanceResultadosLayout);
        DesktopPaneBalanceResultadosLayout.setHorizontalGroup(
            DesktopPaneBalanceResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 649, Short.MAX_VALUE)
        );
        DesktopPaneBalanceResultadosLayout.setVerticalGroup(
            DesktopPaneBalanceResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 318, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPaneBalanceResultados)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPaneBalanceResultados)
        );

        jTabbedPane1.addTab("Balance Resultados", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
               // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jTabbedPane1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MousePressed
        if(this.jTabbedPane1.getSelectedIndex()==0){
            IntFrmPlanCuentas ifc = new IntFrmPlanCuentas();     
            ((BasicInternalFrameUI)ifc.getUI()).setNorthPane(null); //ocultar internal frame
            ifc.parent=this;
            ifc.setSize(825, 350);
            DesktopPanePlanCuentas.add(ifc);        
            ifc.show();
        }         
        if(this.jTabbedPane1.getSelectedIndex()==1){
            IntFrmLibroDiario ifc = new IntFrmLibroDiario();     
            ((BasicInternalFrameUI)ifc.getUI()).setNorthPane(null); //ocultar internal frame
            ifc.parent=this;
            ifc.setSize(825, 350);
            DesktopPaneLibroDiario.add(ifc);        
            ifc.show();
        } 
        if(this.jTabbedPane1.getSelectedIndex()==2){
            IntFrmAsientoContable ifc = new IntFrmAsientoContable();     
            ((BasicInternalFrameUI)ifc.getUI()).setNorthPane(null); //ocultar internal frame
            ifc.parent=this;
            ifc.setSize(825, 350);
            DesktopPaneAsientoContable.add(ifc);        
            ifc.show();
        }
        if(this.jTabbedPane1.getSelectedIndex()==3){
            IntFrmLibroMayor ifc = new IntFrmLibroMayor();     
            ((BasicInternalFrameUI)ifc.getUI()).setNorthPane(null); //ocultar internal frame
            ifc.parent=this;
            ifc.setSize(825, 350);
            DesktopPaneLibroMayor.add(ifc);        
            ifc.show();
        }  
        if(this.jTabbedPane1.getSelectedIndex()==4){
            IntFrmBalanceComprobacion ifc = new IntFrmBalanceComprobacion();     
            ((BasicInternalFrameUI)ifc.getUI()).setNorthPane(null); //ocultar internal frame
            ifc.parent=this;
            ifc.setSize(825, 350);
            DesktopPaneBalanceComprobacion.add(ifc);        
            ifc.show();
        }         
        if(this.jTabbedPane1.getSelectedIndex()==5){
            IntFrmBalanceGeneral ifc = new IntFrmBalanceGeneral();     
            ((BasicInternalFrameUI)ifc.getUI()).setNorthPane(null); //ocultar internal frame
            ifc.parent=this;
            ifc.setSize(825, 350);
            DesktopPaneBalanceGeneral.add(ifc);        
            ifc.show();
        }
        if(this.jTabbedPane1.getSelectedIndex()==6){
            IntFrmBalanceResultados ifc = new IntFrmBalanceResultados();     
            ((BasicInternalFrameUI)ifc.getUI()).setNorthPane(null); //ocultar internal frame
            ifc.parent=this;
            ifc.setSize(825, 350);
            DesktopPaneBalanceResultados.add(ifc);        
            ifc.show();
        }       
    }//GEN-LAST:event_jTabbedPane1MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DesktopPaneAsientoContable;
    private javax.swing.JDesktopPane DesktopPaneBalanceComprobacion;
    private javax.swing.JDesktopPane DesktopPaneBalanceGeneral;
    private javax.swing.JDesktopPane DesktopPaneBalanceResultados;
    private javax.swing.JDesktopPane DesktopPaneLibroDiario;
    private javax.swing.JDesktopPane DesktopPaneLibroMayor;
    public javax.swing.JDesktopPane DesktopPanePlanCuentas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
